// import {route_activ} from "./";
// import {route_auxtip} from "./";
// import {route_cargops} from "./";
// import {route_ciuda} from "./";
// import {route_corres} from "./";
// import {route_depco} from "./";
// import {route_holding} from "./";
// import {route_macorr} from "./";
// import {route_remidep} from "./";
// import {route_rescorr} from "./";
// import {route_serco} from "./";
// import {route_terce} from "./";
// import {route_tipco} from "./";
// import {route_unifun} from "./";
// import {route_usuar} from "./";
import { RouteEntry } from "./route.entry";

// export const ACTIV = route_activ;
// export const AUXTIP = route_auxtip;
// export const CARGOPS = route_cargops;
// export const CIUDA = route_ciuda;
// export const CORRES = route_corres;
// export const DEPCO = route_depco;
// export const HOLDING = route_holding;
// export const MACORR = route_macorr;
// export const REMIDEP = route_remidep;
// export const RESCORR = route_rescorr;
// export const SERCO = route_serco;
// export const TERCE = route_terce;
// export const TIPCO = route_tipco;
// export const UNIFUN = route_unifun;
// export const USUAR = route_usuar;
export const Entrys = RouteEntry;
